### ISSUE TITLE
Give commit/release permission to Assk

### ISSUE THREAD

**Issue by prceasar** [takari/io.takari.incrementalbuild#32]
Since I am a Product Manager now and no longer do much development, it makes sense for someone else to take the reins of being the committer/releaser for this project at sfdc. Can you give permissions to Assk (https://github.com/Assk) for this? @jvanzyl

**Comment by mosabua** [comment]
Can @Assk  please submit a signed Takari CLA .. then I can give him access.

**Comment by Assk** [comment]
Thanks @mosabua ....Should I scan and attach the signed copy here?

**Comment by mosabua** [comment]
Send to the email in the CLA please

**Comment by mosabua** [comment]
Provided same write access as for @prceasar  now to @Assk
