### ISSUE TITLE
Compilation fails with Java 8 when using anonymous classes

### ISSUE THREAD

**Issue by jyrkiput** [takari/io.takari.incrementalbuild#4]
Compilation fails with 

    java.lang.IllegalStateException: Unexpected input change /home/jyrki/projects/takari/takari-anonymous-class-java8-bug/src/main/java/fi/sysart/takari/App.java
	at io.takari.incrementalbuild.spi.DefaultBuildContext.commit(DefaultBuildContext.java:934)

when using Java 8. This compiles fine with Java 7. Minimal project and logs are available at  https://github.com/jyrkiput/takari-anonymous-class-java8-bug 
https://github.com/jyrkiput/takari-anonymous-class-java8-bug/blob/master/java7.log
https://github.com/jyrkiput/takari-anonymous-class-java8-bug/blob/master/java8.log

**Comment by md-5** [comment]
Same issue:

````
Apache Maven 3.2.3 (33f8c3e1027c3ddde99d3cdebad2656a31e8fdf4; 2014-08-12T06:58:10+10:00)
Maven home: /home/michael/Data/Apps/apache-maven-3.2.3
Java version: 1.8.0_40-internal, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_AU, platform encoding: UTF-8
OS name: "linux", version: "3.16.0-28-generic", arch: "amd64", family: "unix"
```

**Comment by md-5** [comment]
Also if you're curious the class that fails:
````
package org.bukkit.entity;

/**
 * Represents a Weather related entity, such as a storm
 */
public interface Weather extends Entity {}
````

Entire src is here: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/browse (nb: not using Takari there yet since it doesn't work!)

**Comment by ifedorenko** [comment]
@md-5 your jdk version looks odd. Can you confirm this is one of JDK available from http://www.oracle.com/technetwork/java/javase/downloads/index.html ?

As I mentioned earlier, OpenJDK is not supported. From your java home you appear to be using OpenJDK, but I don't know what 1.8.0_40-internal actually means.

**Comment by md-5** [comment]
>As I mentioned earlier, OpenJDK is not supported. From your java home you appear to be using OpenJDK, but I don't know what 1.8.0_40-internal actually means.

Its the version in Ubuntu's 14.10 repos:
http://packages.ubuntu.com/utopic/openjdk-8-jdk

**Comment by ifedorenko** [comment]
Please use reasonably recent Oracle JDK. OpenJDK is not supported.

**Comment by md-5** [comment]
Guess no Takari for me then,

Is no one actually interested in finding the cause of this?

**Comment by mizdebsk** [comment]
I think that merging #5 may fix this issue.
